"""
ROS1 XML Launch file generator.

Generates launch files compatible with the mission_manger node
from the uav_px4_ctrl package (mission_manger.cpp).

The generated launch file structure mirrors:
    /UAV-Super/src/uav_px4_ctrl/launch/mission_manger.launch
"""

from datetime import datetime
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class LaunchConfig:
    """Configuration for generating a ROS1 launch file.

    All fields correspond directly to the <arg> and <param>
    tags in the reference mission_manger.launch.
    """
    # Package and node names
    pkg: str = "uav_px4_ctrl"
    node_type: str = "mission_manger"
    node_name: str = "mission_manger"

    # ROS topics
    odom_topic: str = "/localization"
    pose_topic: str = "/mavros/local_position/pose"
    goal_topic: str = "/goal_pose"

    # Mission parameters
    distance_threshold: float = 0.5
    wait_time: float = 5.0
    start_delay: float = 3.0
    topic_timeout: float = 2.0
    mission_cycle: bool = True

    # Waypoint string (generated by WaypointManager.to_waypoint_string())
    waypoints: str = "[]"

    # Metadata
    generator_version: str = "1.0"
    description: str = ""

    def to_dict(self) -> dict:
        """Serialize config to a dictionary for JSON persistence."""
        return {
            'pkg': self.pkg,
            'node_type': self.node_type,
            'node_name': self.node_name,
            'odom_topic': self.odom_topic,
            'pose_topic': self.pose_topic,
            'goal_topic': self.goal_topic,
            'distance_threshold': self.distance_threshold,
            'wait_time': self.wait_time,
            'start_delay': self.start_delay,
            'topic_timeout': self.topic_timeout,
            'mission_cycle': self.mission_cycle,
            'description': self.description,
        }

    @classmethod
    def from_dict(cls, d: dict) -> 'LaunchConfig':
        """Load config from a dictionary."""
        return cls(
            pkg=d.get('pkg', 'uav_px4_ctrl'),
            node_type=d.get('node_type', 'mission_manger'),
            node_name=d.get('node_name', 'mission_manger'),
            odom_topic=d.get('odom_topic', '/localization'),
            pose_topic=d.get('pose_topic', '/mavros/local_position/pose'),
            goal_topic=d.get('goal_topic', '/goal_pose'),
            distance_threshold=float(d.get('distance_threshold', 0.5)),
            wait_time=float(d.get('wait_time', 5.0)),
            start_delay=float(d.get('start_delay', 3.0)),
            topic_timeout=float(d.get('topic_timeout', 2.0)),
            mission_cycle=bool(d.get('mission_cycle', True)),
            description=str(d.get('description', '')),
        )


def generate_launch_xml(config: LaunchConfig, waypoint_count: int = 0) -> str:
    """Generate a complete ROS1 launch file as an XML string.

    The output exactly mirrors the reference mission_manger.launch format,
    with the waypoint string from config.waypoints embedded as the default
    value of the 'waypoints' arg.

    Args:
        config: LaunchConfig with all parameters set.
        waypoint_count: Number of waypoints (for the header comment).

    Returns:
        Formatted XML string ready to write to a .launch file.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Build the launch XML
    lines = [
        '<launch>',
        '    <!-- ================================================ -->',
        '    <!--  任务管理器 Launch 文件                           -->',
       f'    <!--  生成工具: Mission Generator v{config.generator_version}                  -->',
       f'    <!--  生成时间: {now}                    -->',
    ]

    if config.description:
        lines.append(f'    <!--  说明: {config.description} -->')

    if waypoint_count > 0:
        lines.append(f'    <!--  航点数量: {waypoint_count}                                    -->')

    lines.extend([
        '    <!-- ================================================ -->',
        '',
        '    <!-- 输入话题（odom 优先） -->',
       f'    <arg name="odom_topic" default="{config.odom_topic}"/>',
       f'    <arg name="pose_topic" default="{config.pose_topic}"/>',
       f'    <arg name="goal_topic" default="{config.goal_topic}"/>',
        '    <!-- 到达阈值 -->',
       f'    <arg name="distance_threshold" default="{_fmt_param(config.distance_threshold)}"/>',
        '    <!-- 到达后等待时间 -->',
       f'    <arg name="wait_time" default="{_fmt_param(config.wait_time)}"/>',
        '    <!-- 启动延迟时间 -->',
       f'    <arg name="start_delay" default="{_fmt_param(config.start_delay)}"/>',
        '    <!-- 位置话题超时时间（秒） -->',
       f'    <arg name="topic_timeout" default="{_fmt_param(config.topic_timeout)}"/>',
        '    <!-- 任务循环选项 -->',
       f'    <arg name="mission_cycle" default="{str(config.mission_cycle).lower()}"/>',
        '    <!-- 路径点 -->',
       f'    <arg name="waypoints" default="{_escape_xml(config.waypoints)}"/>',
        '',
        '    <!-- 使用参数 -->',
       f'    <node pkg="{config.pkg}" type="{config.node_type}" '
       f'name="{config.node_name}" output="screen">',
        '        <param name="odom_topic" value="$(arg odom_topic)"/>',
        '        <param name="pose_topic" value="$(arg pose_topic)"/>',
        '        <param name="goal_topic" value="$(arg goal_topic)"/>',
        '        <param name="distance_threshold" value="$(arg distance_threshold)"/>',
        '        <param name="wait_time" value="$(arg wait_time)"/>',
        '        <param name="start_delay" value="$(arg start_delay)"/>',
        '        <param name="topic_timeout" value="$(arg topic_timeout)"/>',
        '        <param name="mission_cycle" value="$(arg mission_cycle)"/>',
        '        <param name="waypoints" value="$(arg waypoints)"/>',
        '    </node>',
        '</launch>',
        '',
    ])

    return '\n'.join(lines)


def save_launch_file(config: LaunchConfig, filepath: str, waypoint_count: int = 0) -> None:
    """Generate and save a launch file to disk.

    Args:
        config: Launch configuration.
        filepath: Output file path (should end with .launch).
        waypoint_count: Number of waypoints for the comment header.
    """
    xml = generate_launch_xml(config, waypoint_count)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(xml)


def _fmt_param(val) -> str:
    """Format a ROS parameter value for XML."""
    if isinstance(val, bool):
        return str(val).lower()
    if isinstance(val, float):
        if val == int(val):
            return f"{val:.1f}"
        return f"{val}"
    return str(val)


def _escape_xml(s: str) -> str:
    """Escape special XML characters in a string."""
    s = s.replace('&', '&amp;')
    s = s.replace('<', '&lt;')
    s = s.replace('>', '&gt;')
    s = s.replace('"', '&quot;')
    s = s.replace("'", '&apos;')
    return s
